
package rs_administrasi.login;

import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.Parameter;
import koneksi.ceklogin;
import rs_administrasi.login.menu_utama;
/**
 *
 * @author COMPUTER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ResultSet st;
    ceklogin db;
    String username, password;
    public Login() {
        initComponents();
        db = new ceklogin(Parameter.HOST_DB, Parameter.USERNAME_DB, Parameter.PASSWORD_DB,
             Parameter.IPHOST, Parameter.PORT);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Mengatur ukuran form sesuai dengan ukuran layar
        setSize(screenSize.width, screenSize.height);
        // Mengatur posisi form di koordinat (0,0) untuk memastikan form berada di pojok kiri atas
        setLocation(0, 0);
      
    }
    
    public void getLogin() {
        if (txt_username.getText().equals("") || txt_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Data login masih kosong !!!");
        }
    
        else {
            try {
                st = db.querySelectAll("user", "username='" + txt_username.getText() + "' and password='" + txt_password.getText() + "'");
                while (st.next()) {
                    username = st.getString("username");
                    password = st.getString("password");
                     rs_administrasi.login.menu_utama h = new menu_utama();
                    h.setVisible(true);
                    this.dispose();
                
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (username == null && password == null) {
                JOptionPane.showMessageDialog(this, "Username dan Password Salah !!!");
            } 
            
            }
        }
    

    public void getUsername() {
        if (txt_username.getForeground().equals(Color.LIGHT_GRAY)) {
            txt_username.setForeground(Color.black);
            txt_username.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_username.setBorder(null);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 360, 40));

        txt_password.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_password.setBorder(null);
        txt_password.setOpaque(false);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 420, 50));

        btn_login.setBackground(new java.awt.Color(0, 204, 204));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText(".");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 410, 40));

        btn_register.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 102, 255));
        btn_register.setText("Register");
        btn_register.setBorder(null);
        btn_register.setBorderPainted(false);
        btn_register.setContentAreaFilled(false);
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 120, 30));

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loginfix.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        getLogin();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
           rs_administrasi.login.Register h = new rs_administrasi.login.Register();
                    h.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField txt_password;
    public static javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
