/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import javax.swing.JPanel;

/**
 *
 * @author COMPUTER
 */
public class data_pasien extends javax.swing.JFrame {

    /**
     * Creates new form data_pasien
     */
    public data_pasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idpasien = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_riwayatsakit = new javax.swing.JTextField();
        txt_gender = new javax.swing.JTextField();
        txt_agama = new javax.swing.JTextField();
        txt_namapasien = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        txt_telpon = new javax.swing.JTextField();
        txt_pendidikan = new javax.swing.JTextField();
        txt_pekerjaan = new javax.swing.JTextField();
        txt_kerjaortu = new javax.swing.JTextField();
        txt_telportu = new javax.swing.JTextField();
        nama_dokter = new javax.swing.JTextField();
        txt_namapasangan = new javax.swing.JTextField();
        txt_usia = new javax.swing.JTextField();
        jDateTimePicker1 = new uz.ncipro.calendar.JDateTimePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_keluhan = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_tgllahir = new uz.ncipro.calendar.JDateTimePicker();
        cb_status = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txt_kodedokter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idpasien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_idpasien.setText("\n");
        txt_idpasien.setBorder(null);
        getContentPane().add(txt_idpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 320, 40));

        txt_alamat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_alamat.setText("\n");
        txt_alamat.setBorder(null);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 320, 40));

        txt_riwayatsakit.setText("\n");
        txt_riwayatsakit.setBorder(null);
        getContentPane().add(txt_riwayatsakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 320, 40));

        txt_gender.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_gender.setText("\n");
        txt_gender.setBorder(null);
        getContentPane().add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 320, 40));

        txt_agama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_agama.setText("\n");
        txt_agama.setBorder(null);
        getContentPane().add(txt_agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 320, 40));

        txt_namapasien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_namapasien.setText("\n");
        txt_namapasien.setBorder(null);
        getContentPane().add(txt_namapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 320, 40));

        jTextField8.setText("\n");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 320, 40));

        txt_telpon.setText("\n");
        txt_telpon.setBorder(null);
        getContentPane().add(txt_telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 320, 40));

        txt_pendidikan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_pendidikan.setText("\n");
        txt_pendidikan.setBorder(null);
        getContentPane().add(txt_pendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 320, 40));

        txt_pekerjaan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_pekerjaan.setText("\n");
        txt_pekerjaan.setBorder(null);
        getContentPane().add(txt_pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 320, 40));

        txt_kerjaortu.setBorder(null);
        getContentPane().add(txt_kerjaortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 320, 40));

        txt_telportu.setBorder(null);
        getContentPane().add(txt_telportu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 320, 40));

        nama_dokter.setBorder(null);
        getContentPane().add(nama_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 230, 40));

        txt_namapasangan.setBorder(null);
        getContentPane().add(txt_namapasangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 320, 40));

        txt_usia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_usia.setText("\n");
        txt_usia.setBorder(null);
        getContentPane().add(txt_usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 320, 40));

        jDateTimePicker1.setDisplayFormat("d/M/yyyy");
        getContentPane().add(jDateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 310, 40));

        txt_keluhan.setColumns(20);
        txt_keluhan.setRows(5);
        txt_keluhan.setText("\n");
        txt_keluhan.setBorder(null);
        jScrollPane1.setViewportView(txt_keluhan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 330, 110));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("Pilih\n");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 440, -1, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText(".");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 170, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText(".\n");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 610, 180, 30));

        txt_tgllahir.setDisplayFormat("d/M/yyyy");
        getContentPane().add(txt_tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 310, 40));

        cb_status.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Menikah", "Menikah", "Cerai Hidup", "Cerai Mati", " " }));
        getContentPane().add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 310, 40));

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penyakit Dalam", "Anak", "Syaraf", "THT", "Bedah", "Kulit dan Kelamin", "Mata", " ", " " }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 240, 40));

        txt_kodedokter.setBorder(null);
        getContentPane().add(txt_kodedokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 230, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\Home (2).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     master.pilihdokter h = new pilihdokter();
        h.setVisible(true);
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         master.menu_utama h = new menu_utama();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private uz.ncipro.calendar.JDateTimePicker jDateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField nama_dokter;
    private javax.swing.JTextField txt_agama;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_idpasien;
    private javax.swing.JTextArea txt_keluhan;
    private javax.swing.JTextField txt_kerjaortu;
    public static javax.swing.JTextField txt_kodedokter;
    private javax.swing.JTextField txt_namapasangan;
    private javax.swing.JTextField txt_namapasien;
    private javax.swing.JTextField txt_pekerjaan;
    private javax.swing.JTextField txt_pendidikan;
    private javax.swing.JTextField txt_riwayatsakit;
    private javax.swing.JTextField txt_telpon;
    private javax.swing.JTextField txt_telportu;
    private uz.ncipro.calendar.JDateTimePicker txt_tgllahir;
    private javax.swing.JTextField txt_usia;
    // End of variables declaration//GEN-END:variables
}
