package master;

import icon.tableCustom;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class pilihdokter extends javax.swing.JFrame {

    DefaultTableModel table = new DefaultTableModel();

    public pilihdokter() {
        initComponents();
         icon.tableCustom.apply(jScrollPane2, tableCustom.TableType.DEFAULT);
        koneksi conn = new koneksi();
        koneksi.getKoneksi();

        table_pilih_dokter1.setModel(table);
        table.addColumn("nip");
        table.addColumn("nama");
        table.addColumn("spesialis");
        table.addColumn("jadwal");

        tampilData();
    }

    private void tampilData() {
        try {
            Connection connect = koneksi.getKoneksi();
            Statement sttmnt = connect.createStatement();
            String query = "SELECT nip, nama_dokter, spesialis, jadwal FROM data_dokter";
            ResultSet rslt = sttmnt.executeQuery(query);

            while (rslt.next()) {
                String nip = rslt.getString("nip");
                String namadokter = rslt.getString("nama_dokter");
                String spesialis = rslt.getString("spesialis");
                String jadwal = rslt.getString("jadwal");

                String[] data = {nip, namadokter, spesialis, jadwal};
                table.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_pilih_dokter1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_pilih_dokter1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pilih_dokter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pilih_dokter1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_pilih_dokter1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 409, 402));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_pilih_dokter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pilih_dokter1MouseClicked
        // TODO add your handling code here:
           int row = table_pilih_dokter1.getSelectedRow();
        
        String nip = table.getValueAt(row, 0).toString();
        data_pasien.txt_kodedokter.setText(nip);
        
        String nama = table.getValueAt(row, 1).toString();
        data_pasien.nama_dokter.setText(nama); 
         
//        transaksipembelian1.Tentukan();
        dispose();
    }//GEN-LAST:event_table_pilih_dokter1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_pilih_dokter1;
    // End of variables declaration//GEN-END:variables
}
